<?php
/**
 * Create By xuzhihua
 * author     : xuzhihua
 * createTime : 2020/2/24 10:41 下午
 * description: 现在的努力是为了小时候吹过的牛逼！
 */

namespace app\backend\controller;


use app\common\constants\commonConstants;
use app\common\constants\sessionCacheConstants;
use app\common\vo\ManagerInfo;
use app\common\vo\UnitInfo;
use think\Controller;
use think\facade\Cache;
use think\facade\Session;

class BackendBaseController extends Controller
{
    //数据库连接参数
    public $connection = [];
    //单位信息
    public $unitInfo = [];
    //管理员信息
    public $managerInfo = [];
    //单位标记
    public $flag = '';

    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        //单位标记检测
        if(!$this->checkFlag()){
            $this->redirect(commonConstants::LOGIN_URL.Cache::get(sessionCacheConstants::UNIT_FLAG_SESSION.$this->request->ip()));
        }
        //检测登录状态
        if(!$this->checkLogin()){
            $this->redirect(commonConstants::LOGIN_URL.Cache::get(sessionCacheConstants::UNIT_FLAG_SESSION.$this->request->ip()));
        }
    }

    //检测单位标签
    public function checkFlag(){
        if(Cache::has(sessionCacheConstants::UNIT_FLAG_SESSION.$this->request->ip())){
            $this->connection = Session::get(sessionCacheConstants::UNIT_SQL_SESSION,sessionCacheConstants::UNIT_SQL_SESSION_PREFIX);
            $this->unitInfo = Session::get(sessionCacheConstants::UNIT_INFO_SESSION,sessionCacheConstants::UNIT_INFO_SESSION_PREFIX);
            $this->flag = Session::get(sessionCacheConstants::UNIT_FLAG_SESSION);
            return true;
        }else{
            return false;
        }
    }
    /**
     * 检测登录状态
     */
    public function checkLogin(){
        if(Session::has(sessionCacheConstants::UNIT_LOGIN_SESSION,sessionCacheConstants::UNIT_LOGIN_SESSION_PREFIX)){
            $this->managerInfo = Session::get(sessionCacheConstants::UNIT_LOGIN_SESSION,sessionCacheConstants::UNIT_LOGIN_SESSION_PREFIX);
            return true;
        }else{
            return false;
        }
    }
    public function getUnitInfo() : UnitInfo {
        return (new UnitInfo($this->unitInfo));
    }
    public function getManagerInfo() : ManagerInfo {
        return (new ManagerInfo($this->managerInfo));
    }
}